services:
  - type: web
    name: code-reviewer
    env: static
    buildCommand: npm run build
    staticPublishPath: ./Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
