services:
  - type: web
    name: code-reviewer
    env: static
    staticPublishPath: ./dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
